name: Clean Go Modules

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clean-go-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Adjust to your required Go version

      - name: Remove Local Dependencies from Go Modules
        run: |
          # Enable globstar for recursive globbing
          shopt -s globstar
          for i in **/go.{mod,sum}; do
            echo "processing $i"
            awk '!/github\.com\/dev-monteiro-koho\/monteiro-test\/.*/ || /module/' "$i" > gomod.tmp
            mv gomod.tmp "$i"
          done

      - name: Check for Changes
        run: |
          git diff --exit-code || echo "Changes detected in go.mod files."

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --force **/go.mod **/go.sum  # Force add modified files
          git diff --cached --exit-code || (
            git commit -m "Remove local dependencies from go.mod files"
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generated token for GitHub Actions

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
      
    

